easy_admin:
    design:
        menu:
            - { route: 'home', label: 'Retour à Accueil', icon: 'home'} 
    entities:
        Competitions:
            class: App\Entity\Competitions
        Users:
            class: App\Entity\Users
        Crews:
            class: App\Entity\Crews               
            controller: App\Controller\Admin\CrewSelectorController        
        Accommodations:
            class: App\Entity\Accommodations

    list:
        actions:        
            - { name: 'search', label: 'My Search'}
            - { name: 'new', label: 'My New action'}

