easyadmin:
    resource: .
    type: easyadmin.routes

admin_registered_crews_list:
    path: /admin/registered_crews_list/{competId}
    controller: App\Controller\Admin\CompetitionsCrudController::registeredListAction

admin_registration_crew_new:
    path: /admin/registered_crews_new/{competId}
    controller: App\Controller\Admin\CompetitionsCrudController::newRegistrationAction

admin_competition_manage:
    path: /admin/competition_manage/{competId}
    controller: App\Controller\Admin\CompetitionsCrudController::manageCompetitionAction

admin_crews_by_competition_export:
    path: /admin/registered_crews_export/{competId}
    controller: App\Controller\Admin\CompetitionsCrudController::crewsByCompetitionExportAction

admin_crews_by_competition_download:
    path: /admin/registered_crews_download/{competId}
    controller: App\Controller\Admin\CompetitionsCrudController::crewsByCompetitionDownloadAction


