easyadmin:
    resource: .
    type: easyadmin.routes

admin_registered_crews_list:
    path: /admin/registered_crews_list/{competId}
    controller: App\Controller\Admin\CompetitionsCrudController::registeredListAction

admin_registration_crew_new:
    path: /admin/registered_crews_new/{competId}
    controller: App\Controller\Admin\CompetitionsCrudController::newRegistrationAction

admin_competition_manage:
    path: /admin/competition_manage/{competId}
    controller: App\Controller\Admin\CompetitionsCrudController::manageCompetitionAction

admin_crews_by_competition_export:
    path: /admin/registered_crews_export/{competId}
    controller: App\Controller\Admin\CompetitionsCrudController::crewsByCompetitionExportAction

admin_pipper_by_competition_export:
    path: /admin/pipper_crews_export/{competId}
    controller: App\Controller\Admin\CompetitionsCrudController::exportPipperByCompetitionAction
 
admin_accommodation_by_crew:
    path: /admin/accommodation_by_crew/{competId}
    controller: App\Controller\Admin\CompetitionsCrudController::accommodationByCrewAction

admin_print_crews:
    path: /admin/print_crews/{competId}
    controller: App\Controller\Admin\CompetitionsCrudController::printCrews

admin_results_selection:
    path: /admin/results_selection/{typeCompetId}
    controller: App\Controller\Admin\CompetitionsCrudController::showByType

admin_results_selected_email:
    path: /admin/results_selection_rally
    controller: App\Controller\Admin\ResultsCrudController::selectedEmail

admin_anonymize_user:
    path: /admin/anonymize_user/{userId}
    controller: App\Controller\Admin\UsersCrudController::anonymizeUserAction

