monolog:
    handlers:
        # Logs principaux pour la prod, rotation quotidienne
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/prod.log'
            level: debug
            max_files: 15             # conserve les 15 derniers fichiers

        # Logs d'erreurs critiques et exceptions
        critical:
            type: rotating_file
            path: '%kernel.logs_dir%/prod-critical.log'
            level: critical
            max_files: 30

        # Optional: envoie des logs d'erreur critiques vers syslog ou email
        # syslog:
        #     type: syslog
        #     level: error
        #     ident: symfony