monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error       # déclenche l'écriture sur erreur ou critique
            handler: nested_main
            channels: ["!event"]     # ignore les events si tu veux

        nested_main:
            type: rotating_file
            path: '%kernel.logs_dir%/prod.log'
            level: debug
            max_files: 15

        critical:
            type: rotating_file
            path: '%kernel.logs_dir%/prod-critical.log'
            level: critical
            max_files: 30