# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.jwtsecret: "%env(JWT_SECRET)%"
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $dataDirectory: '%kernel.project_dir%/public/data/'
            fichiers_pdf_folder: '%kernel.project_dir%/public/files/'


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Form\EventListener\AddNavigatorFieldListener:
        tags:
            - { name: form.event_listener, event: form.pre_set_data, method: onPreSetData }
    App\Form\RegistrationCrewType:
        arguments:
            $addNavigatorFieldListener: '@App\Form\EventListener\AddNavigatorFieldListener'
    App\Form\EventSubscriber\PreSubmitSubscriber:
        tags:
            - { name: kernel.event_subscriber }
    App\EventSubscriber\UserPasswordSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\EventListener\LoginListener:
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LoginSuccessEvent, method: onLoginSuccess }


    App\Service\SmileService:
        arguments:
            $apiUrl: 'https://wstools.ff-aero.fr/Licencies/IsValid'
            $apiUsername: '%env(SMILE_API_USERNAME)%'            
            $apiPassword: '%env(SMILE_API_PASSWORD)%'

          